# Generated by Django 2.0.7 on 2018-08-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('describe', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='file')),
            ],
        ),
    ]
