# Generated by Django 2.0.7 on 2018-08-11 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiment', '0001_initial'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiment.Item'),
        ),
        migrations.AddField(
            model_name='examsetting',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiment.Experiment'),
        ),
    ]
