# Generated by Django 2.0.7 on 2018-08-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examsetting',
            old_name='Experiment',
            new_name='experiment',
        ),
    ]
