# Generated by Django 2.0.7 on 2018-08-10 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiment', '0005_auto_20180808_1141'),
        ('exam', '0002_auto_20180807_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('a', models.CharField(blank=True, max_length=50)),
                ('b', models.CharField(blank=True, max_length=50)),
                ('c', models.CharField(blank=True, max_length=50)),
                ('d', models.CharField(blank=True, max_length=50)),
                ('answer', models.CharField(max_length=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiment.Item')),
            ],
        ),
    ]
