# Generated by Django 2.0.7 on 2018-08-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_examsetting_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsetting',
            name='questions',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
