# Generated by Django 2.0.7 on 2018-08-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='openid',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='123456', max_length=20),
        ),
    ]
