# Generated by Django 2.0.7 on 2018-08-06 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('term', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Classes'),
        ),
    ]
