# Generated by Django 2.0.7 on 2018-08-06 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20180806_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xh', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=5)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Classes')),
            ],
        ),
    ]
